
.PHONY: clean run build
#target: dependences
#      command
CC = g++

CFLAGS = -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D _DEBUG -D _EJUDGE_CLIENT_SIDE

build: solver

main.o: main.cpp
	$(CC) $(CFLAGS) -c main.cpp

input.o: input.cpp
	$(CC) $(CFLAGS) -c input.cpp

print.o: print.cpp
	$(CC) $(CFLAGS) -c print.cpp

size.o: size.cpp
	$(CC) $(CFLAGS) -c size.cpp


solver: main.o input.o print.o size.o
	$(CC) $(CFLAGS) main.o input.o size.o -o solver

clean:
	rm *.o

main_test: main_test.o
	$(CC) $(CFLAGS) main_test.o -o main_test

run:
	.\solver.exe
